volumes:
  db-store:

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    restart: always
    env_file: .env
    container_name: app
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    ports:
      - 9000:9000

  caddy:
    image: caddy:2.7.6
    restart: unless-stopped
    env_file: .env
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config
      - type: bind
        source: ./src
        target: /workspace
    ports:
      - 80:80
      - 443:443
      - 2019:2019
    depends_on:
      - app

  mailpit:
    image: axllent/mailpit
    env_file: .env
    restart: always
    container_name: mailpit
    ports:
      - target: 8025
        published: ${MAILPIT_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host