version: '3.8'

volumes:
  db-store:

services:
  dashboard:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile.dashboard
    restart: always
    env_file: .env
    container_name: dashboard
    volumes:
      - type: bind
        source: ./src
        target: /workspace

  dashboard-ws:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile.ws
    restart: always
    env_file: .env
    container_name: dashboard-ws
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    ports:
      - '6001:6001'

  nginx:
      build:
        context: .
        dockerfile: ./infra/docker/nginx/Dockerfile
      ports:
        - target: 8080
          published: 8080
          protocol: tcp
          mode: host
      volumes:
        - type: bind
          source: ./src
          target: /workspace

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    container_name: db
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-fluffici_test}
      - MYSQL_USER=${DB_USERNAME:-phper}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
