version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile.dashboard
    hostname: dashboard
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    environment:
      APP_BUILD_TARGET: ${APP_BUILD_TARGET}
      APP_NAME: ${APP_NAME}
      APP_DEBUG: ${APP_DEBUG}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      ASSET_URL: ${ASSET_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER}
      PUSHER_HOST: ${PUSHER_HOST}
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_APP_KEY: ${PUSHER_APP_KEY}
      PUSHER_APP_SECRET: ${PUSHER_APP_SECRET}
      PUSHER_SCHEME: ${PUSHER_SCHEME}
      PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
      FLARE_KEY: ${FLARE_KEY}
    networks:
      - net-db

  dashboard-ws:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile.ws
    hostname: dashboard-ws
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    environment:
        APP_NAME: ${APP_NAME}
        APP_DEBUG: ${APP_DEBUG}
        APP_ENV: ${APP_ENV}
        APP_KEY: ${APP_KEY}
        BROADCAST_DRIVER: ${BROADCAST_DRIVER}
        PUSHER_HOST: ${PUSHER_HOST}
        PUSHER_APP_ID: ${PUSHER_APP_ID}
        PUSHER_APP_KEY: ${PUSHER_APP_KEY}
        PUSHER_APP_SECRET: ${PUSHER_APP_SECRET}
        PUSHER_SCHEME: ${PUSHER_SCHEME}
        PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
        FLARE_KEY: ${FLARE_KEY}
    networks:
      - net-db

  nginx:
      build:
        context: .
        dockerfile: ./infra/docker/nginx/Dockerfile
      hostname: nginx-dashboard
      volumes:
        - type: bind
          source: ./src
          target: /workspace
      networks:
        - net-db

  db:
    image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
    hostname: db
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
        MYSQL_DATABASE: ${DB_DATABASE:-fluffici_test}
        MYSQL_USER: ${DB_USERNAME:-phper}
        MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - net-db

networks:
  net-db:
    name: db-net

volumes:
  db-store:
