jpeg_quality = 80

[serve]
    as = "WEBP"
    quality = 90.0

[tags]
    # File Uploads
    [tags.attachments]
        max_size = 20000000
        serve_if_field_present = ["object_id", "user_id"]

    # User Avatars
    [tags.avatars]
        max_size = 4000000
        restrict_content_type = "Image"
        serve_if_field_present = ["object_id", "user_id"]
    
    # User Profile Backgrounds
    [tags.photos]
        max_size = 6000000
        restrict_content_type = "Image"
        serve_if_field_present = ["object_id"]
    
    # Banners
    [tags.banners]
        max_size = 6000000
        restrict_content_type = "Image"
        serve_if_field_present = ["object_id", "event_id"]
