name: Create and publish

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get git short hash
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Build the Dashboard
        run: docker build . -t dashboard

      - name: Set Tags to Dashboard image
        run: |
          docker tag dashboard ghcr.io/fluffici/dashboard:latest
          docker tag dashboard ghcr.io/fluffici/dashboard:${{ env.GITHUB_SHA_SHORT }}
      - name: Push images to registry
        run: docker push --all-tags ghcr.io/fluffici/dashboard

      - name: Deploy new image
        run: |
          docker run --rm \
            -e HOST="https://portainer.fluffici.eu" \
            -e API_KEY="${{ secrets.PORTAINER_API_KEY }}" \
            -e DOCKER_VERSION="${{ env.GITHUB_SHA_SHORT }}" \
            -e ENDPOINT_ID="1" \
            -e STACK_ID="9" \
            -e STACK_VARIABLE_NAME="DASHBOARD_VERSION" \
            -e PULL_IMAGES="true" \
            registry.gitlab.com/technikcz/portainer-service-updater:4
