#
name: Create and publish a Docker image

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to ghcr
        run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Dashboard and push
        run: docker build .Dockerfile -t ghcr.io/fluffici/dashboard:latest && docker push ghcr.io/fluffici/dashboard:latest
